<h1>Editar Produto</h1>

<form method="post" action="<?= $this->url('application', ['action'=> 'editar']) ?>">
	<input type="hidden" name="id" value="<?= $produto->getId(); ?>">
	<div class="form-group">
		<label>Nome</label>
		<input type='text' name="nome" class="form-control" value="<?= $produto->getNome(); ?>">
	</div>

	<div class="form-group">
		<label>Preço</label>
		<input type='number' name="preco" class="form-control" value="<?= $produto->getPreco(); ?>">
	</div>

	<div class="form-group">
		<label>Descrição</label>
		<textarea class="form-control" name="descricao"><?= $produto->getDescricao(); ?></textarea>
	</div>
	<div class="form-group">
		<input type="submit" class="btn btn-primary" value="Salvar Alterações">
	</div>
</form>